spring.application.name=API-GATEWAY
server.port=8085

# ==========================
# Eureka Configuration
# ==========================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ==========================
# Gateway Routes
# ==========================

# Auth Service
spring.cloud.gateway.mvc.routes[0].id=auth-service
spring.cloud.gateway.mvc.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/auth/**

# Job Service
spring.cloud.gateway.mvc.routes[1].id=job-service
spring.cloud.gateway.mvc.routes[1].uri=lb://JOB-SERVICE
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/jobs/**

# Candidate Service
spring.cloud.gateway.mvc.routes[2].id=candidate-service
spring.cloud.gateway.mvc.routes[2].uri=lb://CANDIDATE-SERVICE
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/**

# AI Screening Service
spring.cloud.gateway.mvc.routes[3].id=ai-screening-service
spring.cloud.gateway.mvc.routes[3].uri=lb://AI-SCREENING-SERVICE
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/screening/**